<?php
namespace Math;


require_once '../../src/Math/Trigonometry.php';

/**
 * Test class for Trigonometry.
 * Generated by PHPUnit on 2011-03-26 at 21:35:31.
 */
class TrigonometryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * Sets up the fixture
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * Tests of sine
     */
    public function testSin()
    {
        $sin1 = Trigonometry::sin(M_PI_2);
        $sin2 = Trigonometry::sin(M_PI_4);
        $sin3 = Trigonometry::sin(1E-15);
        $this->assertEquals(1, $sin1);
        $this->assertEquals(0.70710678118655, $sin2, '', 1E-10);
        $this->assertEquals(0, $sin3);
    }

    /**
     * Test of cosine
     */
    public function testCos()
    {
        $cos1 = Trigonometry::cos(M_PI_2);
        $cos2 = Trigonometry::cos(M_PI_4);
        $cos3 = Trigonometry::cos(1E-15);
        $this->assertEquals(0, $cos1);
        $this->assertEquals(0.70710678118655, $cos2, '', 1E-10);
        $this->assertEquals(1, $cos3);
    }

    /**
     * @todo Implement testTan().
     */
    public function testTan()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSec().
     */
    public function testSec()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testCsc().
     */
    public function testCsc()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testCot().
     */
    public function testCot()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testAsin().
     */
    public function testAsin()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testAcos().
     */
    public function testAcos()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testAtan().
     */
    public function testAtan()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testAtan2().
     */
    public function testAtan2()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testAsec().
     */
    public function testAsec()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testAcsc().
     */
    public function testAcsc()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testAcot().
     */
    public function testAcot()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSinh().
     */
    public function testSinh()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testCosh().
     */
    public function testCosh()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testTanh().
     */
    public function testTanh()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSech().
     */
    public function testSech()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testCsch().
     */
    public function testCsch()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testCoth().
     */
    public function testCoth()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testAsinh().
     */
    public function testAsinh()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testAcosh().
     */
    public function testAcosh()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testAtanh().
     */
    public function testAtanh()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testAsech().
     */
    public function testAsech()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testAcsch().
     */
    public function testAcsch()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testAcoth().
     */
    public function testAcoth()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
